name: Notify website to update

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: |
          curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}